
export const menuItems = [
    {
        title:'Главная',
        href:''
    },
    {
        title:'О курорте',
        href:'',
        ul:[
            {
                title:'Новости и статьи',
                href:''
            },
            {
                title:'Сотрудничество',
                href:''
            },
            {
                title:'',
                href:'Отзывы'
            }
        ]
    },
    {
        title:'Программы',
        href:''
    },
    {
        title:'Номера',
        href:''
    },
    {
        title:'Процедуры',
        href:''
    },
    {
        title:'Развлечения',
        href:''
    },
    {
        title:'Прайс',
        href:''
    },
    {
        title:'Галерея',
        href:''
    },
    {
        title:'Контакты',
        href:''
    },
]